# Used when a commit is pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: ci
on: push

env:
  CELERITAS_DISABLE_DECOMP: true
  ORG_GRADLE_PROJECT_celeritas_target_versions_pattern: ".*"
  ORG_GRADLE_PROJECT_celeritas_target_subprojects_pattern: ".*"

jobs:
  build:
    if: false
    runs-on: ubuntu-large

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
            21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.4
      - name: Build all packaged jars
        run: ./gradlew packageJar --info --stacktrace
      - name: Show checksums
        run: find build/libs -name \*.jar | sort | xargs sha256sum