name: gtnh
on: [push, workflow_dispatch]

env:
  CELERITAS_DISABLE_DECOMP: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
            21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.4
      - name: Build common
        run: ./gradlew :common:build --stacktrace
      - name: Publish common to the GTNH maven
        if: github.event_name == 'workflow_dispatch'
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew :common:publishMavenJavaPublicationToGtnhRepository
